language: php

php:
  - 5.6
  - 7.0

sudo: false

before_install:
  - composer self-update
  - wget https://scrutinizer-ci.com/ocular.phar
  - curl -O https://github.com/ApiGen/ApiGen.github.io/raw/master/apigen.phar

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
- phpunit --configuration phpunit.dist.xml
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
